services:
  blogHubDb:
    container_name: blogHubDb
    image: custom-sqlserver 
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Zoh@ib26
    networks:
      - blogHub
    volumes:
      - sqlserver_data:/var/opt/mssql

  web:
    container_name: web
    build:
      context: .
      dockerfile: Web/Dockerfile
    ports:
      - 5000:8080
    depends_on:
      - blogHubDb
    networks:
      - blogHub

networks:
  blogHub:
    driver: bridge

volumes:
  sqlserver_data: