using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BlogHub.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddedPostAUtogeneratedKey : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
           
            migrationBuilder.DropColumn(
                name: "TimeToRead",
                table: "Posts");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
          

            migrationBuilder.AddColumn<int>(
                name: "TimeToRead",
                table: "Posts",
                type: "int",
                nullable: false,
                defaultValue: 0);
        }
    }
}
